apiVersion: v1
kind: Namespace
metadata:
  name: proxmox-mock
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: proxmox-mock-vm
  namespace: proxmox-mock
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: proxmox-mock-vm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
      volumes:
        - name: containerdisk
          containerDisk:
            image: ghcr.io/realagiorganization/proxmox-mock:latest
